### ISSUE TITLE
Team Detection

### ISSUE THREAD

**Issue by BrendanFish** [Innovators-3311/FtcRobotController2022#10]
Can be used for autonomous and compass correcting.

Completed when: We can tell which teakm we are on before the match.

**Comment by BrendanFish** [comment]
Using a switch to dictate team?

**Comment by mistrspidr** [comment]
I am making a class called `TeamDetection`
it will provide two `public` `Boolean` variables:
`redTeam`
`blueTeam`
This will require a switch and a digital input.
The constructor will require a hardware map
