### ISSUE TITLE
Team cone sleeve 

### ISSUE THREAD

**Issue by Glorfindel29** [Innovators-3311/FtcRobotController2022#11]
We need the cone sleeve to score 10 extra points.
Restrictions for assembly 

The intent is for Teams to add custom images and Team Numbers to the Signal Sleeve template and print their
customized Signal Sleeve ahead of time. Add-ons after printing are not allowed. Please see Game Manual
Part 2 for rules on how the Signal Sleeve is used in gameplay.

<SS02> Images - A Signal Sleeve image may not resemble a current season’s Signal image or any current
season’s COTS game elements. The Team supplied images must fit completely within the designated areas
on the template.
<SS03> Team Number – Signal Sleeves must be labeled with their Team number  The numbers must be legible when viewed from a distance of 12 inches (30.48 cm) away. 
The Team number appears below each image as indicated on the Signal Sleeve template. 
<SS04> Material –
a. The Signal Sleeve may be made from any thin, opaque sheet material.
b. The entire Signal Sleeve, including the images and team number, must be created as a single object
using a printer (laser or inkjet) or equivalent printing technology. No add-on taped or glued items after
printing are allowed (e.g., glitter, images, retro reflective tape).
c. Team Numbers may not be added after the Signal Sleeve is printed.
d. Tape or adhesive are the only allowed methods of holding the Signal Sleeve in its final cone-shaped
form.

The signal sleeve template and instructions can be located at https://www.firstinspires.org/resourcelibrary/ftc/game-and-season-info.

We are done when we have like 10 copies of sleeve do to its durability.

**Comment by Carl4** [comment]
Good issue.  I like that it's clear, concise, small, and achievable. Next, we need the other software development issues to make our robot detect and act on the sleeve it sees at startup.
