### ISSUE TITLE
Vuforia Image Detection

### ISSUE THREAD

**Issue by Glorfindel29** [Innovators-3311/FtcRobotController2022#15]
Start using Vuforia in are code to identify are position and  Identify objects.
Add more objects for the robots to identify, such as poles (Would be nice if we separated into 4 different groups them by height), cone, and the yet to be made signal sleeve.

Done when we get the robot moving base of input from Vuforia 

==================================================================================
P.S I think we you remove the issues concerning roadrunner since we are not using it.

**Comment by BrendanFish** [comment]
our*
