### ISSUE TITLE
Initial Localizer

### ISSUE THREAD

**Issue by BrendanFish** [Innovators-3311/FtcRobotController2022#16]
Have the code tell you X, Y, xVelocity, and yVelocity. Also, use the code to figure out where you are on the field.

Completed when: 
- The robot can tell where it is on the field and 
- displays where it thinks it is.

Note: it is not necessary that the robot ALWAYS know where it is. For this initial version, we can simply be wrong of vuforia isn't available.

**Comment by Carl4** [comment]
I created issue #17, which will be necessary to verify that this works right. 


https://github.com/Innovators-3311/FtcRobotController2022/issues/17
